### ISSUE TITLE
Dropping single callback reference invalidates the entire callback

### ISSUE THREAD

**Issue by arg0d** [NordSecurity/uniffi-bindgen-cs#79]
Callback references are counted incorrectly, dropping a single callback reference invalidates all other references.

```diff
diff --git a/dotnet-tests/UniffiCS.BindingTests/TestCallbacksFixture.cs b/dotnet-tests/UniffiCS.BindingTests/TestCallbacksFixture.cs
index 2ae7d9c..afdab55 100644
--- a/dotnet-tests/UniffiCS.BindingTests/TestCallbacksFixture.cs
+++ b/dotnet-tests/UniffiCS.BindingTests/TestCallbacksFixture.cs
@@ -189,4 +189,20 @@ public class TestCallbacksFixture
             );
         }
     }
+
+    [Fact]
+    public void ShortLivedCallbackDoesNotInvalidateLongerLivedCallback()
+    {
+        var stringifier = new CsharpStringifier();
+        using (var rustStringifier1 = new RustStringifier(stringifier))
+        {
+            using (var rustStringifier2 = new RustStringifier(stringifier))
+            {
+                Assert.Equal("123", rustStringifier2.FromSimpleType(123));
+            }
+            // `stringifier` must remain valid after `rustStringifier2` drops the reference
+
+            Assert.Equal("123", rustStringifier1.FromSimpleType(123));
+        }
+    }
 }
```

```
  Failed UniffiCS.BindingTests.TestCallbacksFixture.ShortLivedCallbackDoesNotInvalidateLongerLivedCallback [11 ms]
  Error Message:
   uniffi.fixture_callbacks.InternalException : No callback in handlemap '2'
  Stack Trace:
     at uniffi.fixture_callbacks.FfiConverterCallbackInterface`1.Lift(UInt64 handle) in C:\workspace\uniffi-bindgen-cs\dotnet-tests\UniffiCS\gen\fixture_callbacks.cs:line 1541
   at uniffi.fixture_callbacks.ForeignCallbackTypeStoredForeignStringifier.<>c.<.cctor>b__4_0(UInt64 handle, UInt32 method, IntPtr argsData, Int32 argsLength, RustBuffer& outBuf) in C:\workspace\uniffi-bindgen-cs\dotnet-tests\UniffiCS\gen\fixture_callbacks.cs:line 1784
   at uniffi.fixture_callbacks._UniFFILib.uniffi_uniffi_fixture_callbacks_fn_free_ruststringifier(IntPtr ptr, RustCallStatus& _uniffi_out_err)
   at uniffi.fixture_callbacks.RustStringifierSafeHandle.<ReleaseHandle>b__2_0(RustCallStatus& status) in C:\workspace\uniffi-bindgen-cs\dotnet-tests\UniffiCS\gen\fixture_callbacks.cs:line 1271
   at uniffi.fixture_callbacks._UniffiHelpers.<>c__DisplayClass5_0.<RustCall>b__0(RustCallStatus& status) in C:\workspace\uniffi-bindgen-cs\dotnet-tests\UniffiCS\gen\fixture_callbacks.cs:line 275
   at uniffi.fixture_callbacks._UniffiHelpers.RustCallWithError[U,E](CallStatusErrorHandler`1 errorHandler, RustCallFunc`1 callback) in C:\workspace\uniffi-bindgen-cs\dotnet-tests\UniffiCS\gen\fixture_callbacks.cs:line 238
   at uniffi.fixture_callbacks._UniffiHelpers.RustCall[U](RustCallFunc`1 callback) in C:\workspace\uniffi-bindgen-cs\dotnet-tests\UniffiCS\gen\fixture_callbacks.cs:line 269
   at uniffi.fixture_callbacks._UniffiHelpers.RustCall(RustCallAction callback) in C:\workspace\uniffi-bindgen-cs\dotnet-tests\UniffiCS\gen\fixture_callbacks.cs:line 274
   at uniffi.fixture_callbacks.RustStringifierSafeHandle.ReleaseHandle() in C:\workspace\uniffi-bindgen-cs\dotnet-tests\UniffiCS\gen\fixture_callbacks.cs:line 1270
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation)
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Dispose()
   at uniffi.fixture_callbacks.FFIObject`1.Dispose() in C:\workspace\uniffi-bindgen-cs\dotnet-tests\UniffiCS\gen\fixture_callbacks.cs:line 1056
   at UniffiCS.BindingTests.TestCallbacksFixture.ShortLivedCallbackDoesNotInvalidateLongerLivedCallback() in C:\workspace\uniffi-bindgen-cs\dotnet-tests\UniffiCS.BindingTests\TestCallbacksFixture.cs:line 206
```

**Comment by arg0d** [comment]
Fixed by https://github.com/NordSecurity/uniffi-bindgen-cs/pull/90
